version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis

  db:
    image: postgres:13
    container_name: postgres_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:6
    container_name: redis_cache
    ports:
      - "6380:6379"

volumes:
  postgres_data: