from pydantic import BaseModel, HttpUrl
from typing import Optional

class ProductCreate(BaseModel):
    """
    Used as the base class for user input in the create and update(PUT method) endpoints.
    Autogenerated fields (e.g. id) and fields that should be set to the default value while 
    creating a new product (e.g. stars=0, reviews=O, isBestSeller=False) are not part of this class.
    All the other fields are required to be set by the user.
    """
    title: str
    imgUrl: HttpUrl
    price: float
    category_id: int


class ProductUpdate(BaseModel):
    """
    Used as base class for the user input in the partial update endpoint.
    It contains all the Product attributes, and all of them are optional.
    So the user can update whatever fields he want without having to specify all the fields.
    """
    title: Optional[str] = None
    imgUrl: Optional[str] = None
    stars: Optional[float] = 0
    reviews: Optional[int] = 0
    price: Optional[float] = 0
    category_id: Optional[int] = None
    isBestSeller: Optional[bool] = False    


